export const DIVERGENCE_ATTACK_MS = 120;
export const DIVERGENCE_DECAY_MS = 1_400;
export const DIVERGENCE_PULSE_LIFETIME_MS =
  DIVERGENCE_ATTACK_MS + DIVERGENCE_DECAY_MS;
export const DIVERGENCE_MAX_ACTIVE_PULSES = 64;
